language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6.0
  - 3.6.1
  - 3.6.2
  - 3.6.3
  - 3.6.4
  - 3.6.5
  - 3.6.6
  - 3.6.7
  - nightly
  - pypy
  - pypy-5.3
  - pypy3
install:
  - pip install --upgrade .
  - pip list
script:
  - python setup.py test -q
  - if [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then pip install flake8==2.1.0 pep8==1.5.6 && flake8 --version && flake8 pyflakes setup.py; fi
sudo: false
